#!/bin/bash

### BEGIN INIT INFO
# Provides:          kcs
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     S 2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: KAT7 Control Server
# Description:       Provides a KATCP control server listening on port 7147
### END INIT INFO

ulimit -c unlimited
export PATH=/usr/local/sbin:/usr/local/bin:$PATH

case "$1" in
  start)
    kcs -i /usr/local/lib/kcs/init.katcp
    kcplog -a 5 -d -o /var/log/kcplog -s localhost:7147 
    ;;
  stop)
    #kcpcmd -s localhost:7147 halt
    killall kcs
    exit 0
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
  ;;
esac

