#! /bin/sh

ulimit -c unlimited
export PATH=/usr/local/sbin:$PATH

case "$1" in
  start)
    kcs -i /usr/local/lib/kcs/init.katcp
    ;;
  stop)
    kcpcmd -s localhost:7147 halt
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
  ;;
esac

