#! /bin/sh

ulimit -c unlimited
export PATH=/usr/local/sbin:$PATH

case "$1" in
  start)
    kcs -i /usr/local/lib/kcs/init.katcp
    kcplog -d -o /var/log/kcplog -s localhost:7147 
    ;;
  stop)
    #kcpcmd -s localhost:7147 halt
    killall kcs
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
  ;;
esac

