include ../Makefile.inc

INC = -I.

TESTS = test-parse test-line test-rpc test-job

all: $(TESTS)

test-parse: misc.c parse.c
	$(CC) $(CFLAGS) $(INC) -DUNIT_TEST_PARSE -o $@ $^

test-line: misc.c parse.c line.c
	$(CC) $(CFLAGS) $(INC) -DUNIT_TEST_LINE -o $@ $^

test-rpc: misc.c parse.c line.c time.c netc.c rpc.c
	$(CC) $(CFLAGS) $(INC) -DUNIT_TEST_RPC -o $@ $^

test-job: misc.c parse.c line.c time.c netc.c dispatch.c shared.c ts.c log.c notice.c nonsense.c job.c
	$(CC) $(CFLAGS) $(INC) -DUNIT_TEST_JOB -o $@ $^

clean: 
	$(RM) *.o core $(TESTS)
