#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1
stream=$1

kcs_debug "about to run tx-stop"

case "${stream}" in
  k7)
    status=1
    if [ $# -gt 1 ] ; then
      if kcpcmd -k -m tx-stop $2 ; then
        status=0
      fi
    else 
      if kcpcmd -k -m tx-stop ; then
        status=0
      fi 
    fi

    kcs_corr_log
    exit $status

    ;;
  bf*)
    kcs_warn "beamformer streams ${stream} currently tied to stream k7"
    exit 0
    ;;

  *)
    kcs_error "unsupported data stream ${stream}"
    exit 1
    ;;
esac

