#!/bin/bash

source functions.sh

list_source()
{
  source=$1
  host=${2%:*}
  port=${2##*:}

  if [ -z "${host}" ] ; then
    host=unknown
  fi

  if [ -z "${port}" ] ; then
    port=unknown
  fi

  echo "#capture-list ${source} ${host} ${port}"
}

if [ -n "${KCS_CORR_RX}" ] ; then
  list_source k7 ${KCS_CORR_RX}
else
  if [ ! -f ${CORR_CONFIG}/${KATCP_MODE} ] ; then
    kcs_warn "no configuration for ${KATCP_MODE}"
  fi
  rxip=$(grep ^rx_udp_ip ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
  rxport=$(grep ^rx_udp_port ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
  list_source k7 ${rxip}:${rxport}
fi

if kcs_is_beamformer ${KATCP_MODE} ; then
  i=0
  while [ "${i}" -lt "2" ] ; do

    bf_rx=KCS_BF${i}_RX
    if [ -n "${!bf_rx}" ]; then
      list_source bf${i} ${!bf_rx}
    else
      rxip=$(grep ^bf_rx_udp_ip_str_beam${i} ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
      rxport=$(grep ^bf_rx_udp_port_beam${i} ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
      list_source bf${i} ${rxip}:${rxport}
    fi 

    bf_rx=KCS_BF${i}DATA_RX
    if [ -n "${!bf_rx}" ]; then
      list_source bf${i}data ${!bf_rx}
    else
      rxip=$(grep ^bf_rx_udp_ip_str_beam${i} ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
      rxport=$(grep ^bf_rx_udp_port_beam${i} ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
      list_source bf${i}data ${rxip}:${rxport}
    fi 

    bf_rx=KCS_BF${i}META_RX
    if [ -n "${!bf_rx}" ]; then
      list_source bf${i}meta ${!bf_rx}
    else
      rxip=$(grep ^bf_rx_meta_ip_str_beam${i} ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
      rxport=$(grep ^bf_rx_meta_port_beam${i} ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= | tr -d ' ' )
      list_source bf${i}meta ${rxip}:${rxport}
    fi 

    i=$[i+1]

  done
fi

exit 0
