#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1
stream=$1

kcs_debug "about to run tx-stop"

if kcs_is_beamformer ${KATCP_MODE} ; then
  option=${stream}
fi

case "${stream}" in
  k7)
    kcs_info "stopping correlator stream ${stream}"
    ;;
  bf0|bf1)
    if kcs_is_beamformer ${KATCP_MODE} ; then
      kcs_info "stopping beam stream ${stream}"
    else
      kcs_error "datastream ${stream} not available in this mode"
    fi
    ;;
  *)
    kcs_error "unknown data stream ${stream}"
    ;;
esac

if kcpcmd -k -m tx-stop ${option}; then
  status=0
else 
  kcs_warn "${stream} stop failed"
  status=1
fi

kcs_corr_log
exit $status
