#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1
if [ "$1" != "k7" ] ; then
  kcs_error "expected k7 not $1"
  return 1
fi

kcs_debug "about to run tx-start"

status=1

if [ $# -gt 1 ] ; then
  if kcpcmd -k -m tx-start $2 ; then
    status=0
  else 
    kcs_error "corr tx-start failed"
  fi
else 
  if kcpcmd -k -m tx-start ; then
    status=0
  else 
    kcs_error "corr tx-start failed"
  fi 
fi

kcs_corr_log
exit $status
