#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1
if [ "$1" != "k7" ] ; then
  kcs_error "expected k7 not $1"
  return 1
fi

kcs_debug "about to run tx-start"

status=1

if [ $# -gt 1 ] ; then
  kcs_warn "corr package no longer supports a timed start"
fi

if kcpcmd -k -m tx-start ${KCS_CORR_RX%:*} ${KCS_CORR_RX##*:} ; then
  status=0
else 
  kcs_error "corr tx-start failed"
fi

kcs_corr_log
exit $status
