#!/bin/bash

source functions.sh
source beamformer.sh

if [ $# -lt 3 ] ; then
  kcs_error "require three parameters: stream ip port"
  exit 1
fi

output=$1
host=$2
port=$3

case "${output}" in
  k7)
    kcpcmd -s localhost:7147 -k -i -r setenv KCS_CORR_RX $host:$port
    kcs_info "set k7 destination to $host:$port"
    ;;
  bf0|bf1)
    if kcs_is_beamformer ${KATCP_MODE} ; then
      kcpcmd -s localhost:7147 -k -i -r setenv KCS_${output^^*}DATA_RX $host:$port
      kcpcmd -s localhost:7147 -k -i -r setenv KCS_${output^^*}META_RX $host:$port
      kcs_info "set ${output} destination to $host:$port"
    else
      kcs_error "beamformer streams not available in this mode"
      exit 1
    fi
    ;;
  *)
    kcs_error "unsupported data stream ${output}"
    exit 1
    ;;
esac

exit 0
