#!/bin/bash

set -e
source functions.sh

if [ $# -gt 0 ] ; then
  config=/home/jmanley/${1}.conf
else
  if [ -f /etc/corr/config ] ; then
    config=/etc/corr/config
  elif [ -f /home/jmanley/k7-dbes.conf ] ; then
    config=/home/jmanley/k7-dbes.conf
  else
    kcs_error "no correlator config file available"
  fi 
fi

status=1
kcs_debug "running connect"
if kcpcmd -k -r -t 120 connect $config 1000 ; then
  kcs_debug "running initialise"
  if kcpcmd -k -r -t 120 initialise 2 ; then
    status=0
  fi
fi

kcs_corr_log
exit $status
