#!/bin/bash

source functions.sh

export KATCP_SERVER=localhost:7147

if [ ! -f ${CORR_CONFIG} ] ; then
  kcs_error "unable to locate configuration file ${CORR_CONFIG}"
  exit 1
fi

for name in $(grep ^servers.*roach ${CORR_CONFIG} | cut -f2 -d= | tr , ' ') ; do
  if [ ! -f /usr/local/lib/kcs/scripts/${name} ] ; then
    ln -s /usr/local/bin/kcpfmon /usr/local/lib/kcs/scripts/${name} >& /dev/null || kcs_error "unable to alias ${name}"
  fi
  kcpcmd -q -k job process $name exec://${name} || kcs_error "unable to launch lru monitor for ${name}"
done

kcpcmd -q -k job process channel-count exec://channel-count || kcs_error "unable to launch channel count detection routine" 

exit 0
