#!/bin/bash

set -e 
source functions.sh

kcs_info "initiating halt"
xport stop
shutdown -h -t 10 now "katcp halt from ${KATCP_CLIENT}. Use shutdown -c to cancel" < /dev/console >& /dev/console

exit 0
