#!/bin/bash

set -e

source functions.sh

kcs_arg_check $# 3

pps=0
level=0

kcs_info "about to request adc snap shot"

case "$1" in
  pps)
    pps=1
    ;;
  now)
    pps=0
    ;;
  *)
    kcs_error "understand pps or now not ${1}"
    exit 1
    ;;
esac

if [ -z "$2" ] ; then
  level=0
elif [ "$2" -gt 1024 ] ; then
  level=1024
else
  level="$2"
fi

shift 2

if kcs_is_narrowband ${KATCP_MODE} ; then
  if [ "${level}" -gt 0  ] ; then
    kcs_error "threshold triggering not currently supported in narrowband mode"
    exit 1 
  fi
  pps=1
  level=-1
fi

kcpcmd -t 10 -r -k get-adc-snapshots ${pps} ${level} $* | sed -e 's/^\#get-adc-snapshots/#k7-adc-snap-shot/'
