#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 6

antpol=${1}
# ms to s
time=$(echo ${2}/1000 | bc -l | sed -e 's/^\./0./') 
# ms to s
delay=$(echo ${3}/1000 | bc -l | sed -e 's/^\./0./')
# seconds/seconds to ms/ms
drate=${4}
# rad to deg: 180/3.14159265358979323846
fringe=$(echo 57.29578*${5} | bc -l | sed -e 's/^\./0./')
# rads/ms to rotations/second: 1000/(2*3.14159265358979323846
frate=$(echo 159.154943091*${6} | bc -l | sed -e 's/^\./0./')

kcpmsg -s delay -l debug     "${antpol} load time ${2}ms mapped to ${time}s"
kcpmsg -s delay -l debug -m "delay ${3}ms mapped to ${delay}s" "delay rate is ${4}s/s or ms/ms" "fringe offset ${5}rad mapped to ${fringe}deg" "fringe rate ${6}rads/ms mapped to ${frate}rotations/s"

status=1
if kcpcmd -k -r fr-delay-set $antpol $fringe $frate $delay $drate $time now ; then 
  status=0
fi

kcs_corr_log
exit $status
