#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1

freq=$1
mixed=0

kcs_config_numeric coarse_chans
kcs_config_numeric adc_clk

bw=$[adc_clk/2]

if [ "${freq}" -gt "${bw}" ] ; then
  freq=${bw}
fi

channel=$(echo ${coarse_chans}*${freq}/${bw} | bc -l | cut -f1 -d.)
if [ -z ${channel} ] ; then
  channel=0
fi

if [ ${channel} -gt ${coarse_chans} ] ; then
  kcs_error "logic problem, coarse channel ${channel} out of range"
fi

kcs_debug "chansel with ${channel} ${mixed}"

if corr_nb_chansel.py -c ${channel} -m ${mixed} >& /dev/null ; then 
  actual=$[channel*bw/coarse_chans]
  echo "#sensor-list .nbc.frequency.current current\_selected\_center\_frequency Hz integer 0 1000000000"
  echo "#sensor-status $(date +%s)000 1 .nbc.frequency.current nominal ${actual}"
  echo "#return ok ${actual}"
  exit 0
fi

kcs_error "failed to run nb_chansel"
exit 1
