#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1

freq=$1
mixed=0

kcs_config_numeric coarse_chans
kcs_config_numeric adc_clk

if [ $[freq*2] -gt ${adc_clk} ] ; then
  freq=${adc_clk/2}
fi

channel=$(echo 2*${freq}/${adc_clk} | bc -l | cut -f1 -d.)

if [ ${channel} -gt ${coarse_chans} ] ; then
  kcs_error "logic problem, coarse channel ${channel} out of range"
fi

kcs_debug "chansel with ${channel} ${mixed}"

if corr_nb_chansel.py -c ${channel} -m ${mixed} >& /dev/null ; then 
  echo "return ok ${channel}"
fi

kcs_error "failed to run nb_chansel"
exit 1
