#!/bin/bash

set -e 
source functions.sh

kcs_arg_check $# 1

if [ "$#" -le 1 ]  ; then
  kcpcmd -i -k eq-get $1 | tr -d '()' | sed -e 's/^!eq-get/#return/'
else 
  status=1
  if kcpcmd -k -m eq-set $* ; then
    status=0
  fi

  kcs_corr_log
  exit $status
fi
