#!/bin/sh

set -e

source functions.sh

if [ $# -lt 1 ] ; then
  echo "#k7-snap-shot adc"
  exit 0
fi

case "$1" in
  adc)
    kcpcmd -k get-adc-snapshot ${2} | sed -e 's/^!get-adc-snapshot/#return/'
    kcs_corr_log
    ;;
  *)
    kcs_error "unknown snap shot ${1}"
    exit 1
    ;;
esac

