#!/bin/bash

set -e

source functions.sh

if [ $# -lt 1 ] ; then
  exit 1
fi

case "$1" in
  adc)
    kcpcmd -t 10 -k get-adc-snapshot ${2} | sed -e 's/^!get-adc-snapshot/#return/'
    ;;
  quant)
    #kcpcmd -k get-quant-snapshot ${2} | sed -e 's/^!get-quant-snapshot/#return/'
    kcpcmd -t 10 -r -k get-quant-snapshot ${2} | sed -e 's/^#get-quant-snapshot/#return ok/'
    ;;
  *)
    kcs_error "unknown snap shot ${1}"
    exit 1

    ;;
esac

