#!/bin/bash

set -e
source functions.sh

if [ $# -lt 1 ] ; then

  if [ ! -s ${CORR_MAPPING} ] ; then
    kcs_error "no correlator mapping found"
  fi

  antennas=($(cat ${CORR_MAPPING} | tr -s ',' ' '))
  roaches=($(grep '^ *servers_f' ${CORR_CONFIG}/${KATCP_MODE} | cut -f2 -d= |  tr ',' ' '))
  i=0
  while [ ${i} -lt 16 ] ; do
    input=$(kcs_index_to_input ${i})
    echo "#label-input ${antennas[i]:-${input}} $input ${roaches[i/2]}"
    i=$[i+1]
  done

  exit 0
fi

index=$(kcs_input_to_index $1)
result=1

if [ -z "${index}" ] ; then
  kcs_error "unable to parse input label ${index}"
fi

if [ ${index} -ge 16 ] ; then
  kcs_error "input label ${index} unexpectedly large"
fi

index=$(kcs_input_to_index $1)

if [ $# -gt 1 ] ; then
  synonym=${2}
else
  synonym=${1}
fi

kcs_debug "setting label for $1  to ${synonym}"

if kcpcmd -k -r label-input ${index} ${synonym} ; then
  result=0
fi

kcs_corr_log

if [ "${result}" != "0" ] ; then
  exit 1
fi

echo "#return ok ${synonym}"
exit 0

