#!/bin/bash

set -e
source functions.sh

timeout=300
status=1
kcs_debug "running connect"

i=0
while test ${i} -lt ${timeout} && ! kcpcmd -k -r -t 120 connect ; do
  sleep 1
  i=$[i+1]
done

if test ${i} -lt ${timeout} ; then
  kcs_debug "running initialise"
  if kcpcmd -k -r -t 120 initialise 2 ; then
    status=0
  else
     kcs_error "corr initialise failed"
  fi
else
  kcs_error "corr connect failed after ${timeout} attempts"
fi

kcs_corr_log
exit $status
