#!/bin/bash

set -e
source functions.sh

now=$(date +%s)
timeout=150

limit=$[now+timeout]

status=1
kcs_debug "running connect"

while ! kcpcmd -k -r -t 120 connect ; do
  kcs_check_timeout ${limit}
  kcs_corr_log
  sleep 1
  kcs_info "still trying to get corr to connect"
done

kcs_debug "running initialise"
if kcpcmd -k -r -t 120 initialise 2 ; then
  status=0
else
  kcs_error "corr initialise failed"
fi

kcs_corr_log
exit $status
