#!/bin/bash

set -e
source functions.sh

now=$(date +%s)
timeout=150

limit=$[now+timeout]

mode=${0##*-}

if [ -z "${mode}" ] ; then
  kcs_error "no valid mode supplied for mode change"
fi

kcs_debug "chaning mode to $mode"

kcs_change_corr ${mode}

kcs_debug "running connect"

while ! kcpcmd -k -m -t 120 connect ; do
  kcs_check_timeout ${limit}
  kcs_corr_log
  sleep 1
  kcs_info "still trying to get corr to connect"
done

kcs_info "running initialise"
if kcpcmd -k -m -t 120 initialise 2 ; then
  kcs_corr_log
  exit 0
fi

kcs_corr_log
kcs_error "corr initialise failed"

exit 1
