#!/bin/bash

set -e
source functions.sh
source sensors.sh
source beamformer.sh

TARGET_MODE=b16n400M1k

now=$(date +%s)
timeout=150

limit=$[now+timeout]

kcs_debug "changing mode to wideband"

await_mode_sensors

kcs_change_corr ${TARGET_MODE}

kcs_debug "running connect"

while ! kcpcmd -k -m -t 120 connect ${CORR_CONFIG}/${TARGET_MODE} ; do
  kcs_check_timeout ${limit}
  kcs_corr_log
  sleep 1
  kcs_info "still trying to get corr to connect"
done

kcs_info "running initialise"
if ! kcpcmd -k -m -t 120 initialise 2 ; then
  kcs_corr_log
  kcs_error "corr initialise failed"
  exit 1
fi

if ! detect_bf_count $(grep ^servers_x.*roach ${CORR_CONFIG}/${TARGET_MODE} | cut -f2 -d=  ) ; then
  kcs_error "beamformer detection logic failed"
  exit 1
fi

change_mode_sensors ${KATCP_MODE} ${TARGET_MODE}
exit 0
