#!/bin/bash

set -e
source functions.sh

sensor_suffixes=("number\_of\_channels none integer 0 65536" "number\_of\_chanels none integer 0 65536" "number\_of\_channels none integer 0 65536")
sensor_names=(".nbc.channels.coarse" ".nbc.channels.fine" ".wbc.channels")
sensor_keys=(coarse_chans n_chans n_chans)

i=0
while [ $i -lt ${#sensor_names[*]} ] ; do 

  sensor_name=${sensor_names[$i]}
  sensor_key=${sensor_keys[$i]}
  sensor_suffix=${sensor_suffixes[$i]}

  if [ "${sensor_name:0:1}" = "." ] ; then
    relative=${sensor_name:1}
    mode=${relative%%.*}
  else 
    mode=${sensor_name%%.*}
  fi

  config=${CORR_CONFIG}-${mode}

  kcs_debug "attempting to locate $sensor_key in ${config} (mode ${mode}) for ${sensor_name}"

  if [ -e ${config} ] ; then
    sensor_value=$(grep ^${sensor_key} ${config} 2> /dev/null | cut -f2 -d= | tr -d ' ' )
    if [ -z "${sensor_value}" ] ; then
      kcs_error "unable to locate ${sensor_key} in mode ${mode}"
    else 

      echo "#sensor-list ${sensor_name} ${sensor_suffix}"
      echo "#sensor-status $(date +%s)000 1 ${sensor_name} nominal ${sensor_value}"
    fi
  else
    kcs_warn "no config for ${sensor_name} in mode ${mode}" 
  fi

  i=$[i+1]
done

