#!/bin/bash

set -e
source functions.sh

now=$(date +%s)
timeout=150

limit=$[now+timeout]

kcs_debug "changing mode to narrowband"

kcs_change_corr nbc

kcs_debug "running connect"

while ! kcpcmd -k -m -t 120 connect ; do
  kcs_check_timeout ${limit}
  kcs_corr_log
  sleep 1
  kcs_info "still trying to get corr to connect"
done

kcs_info "running initialise"
if kcpcmd -k -m -t 120 initialise 2 ; then
  kcs_corr_log
  echo "#sensor-list .nbc.frequency.current Hz integer 0 65536"
  echo "#sensor-status $(date +%s)000 1 .nbc.frequency.current unknown 0"
  kcs_mode_sensors nbc
  exit 0
fi

kcs_corr_log
kcs_error "corr initialise failed"

exit 1
