#!/bin/bash

function read_check()
{
  value=$(kcpcmd -p 2 -i read sys_scratchpad "$1" "$2")
  if [ "${value}" != "$3" ] ; then
    echo "read test failed: expected ${1}, got ${value}"
    return 1;
  else 
    echo "test ok: result is ${value}"
    return 0;
  fi
}

kcpcmd -i write sys_scratchpad 0 'UOf0'

read_check 0 4 'UOf0'
read_check 1 3 'Of0'
read_check 2 2 'f0'
read_check 3 1 '0'

read_check 0:4  1 'T'
read_check 2:4  1 'c'
read_check 0:2  1 'U'
read_check 0:10 0:8 '='
read_check 0:25 0:7 '`'

