#!/bin/bash

source functions.sh

kcs_debug "about to extract channel count"

echo "#sensor-list channels number\_of\_channels\_in\_wideband\_correlator none integer 0 65536"

channels=$(grep ^n_chans ${CORR_CONFIG} 2> /dev/null | cut -f2 -d= | tr -d ' ' )

if [ -z "${channels}" ] ; then
  kcs_error "unable to extract number of channels from ${CORR_CONFIG}"
else
  echo "#sensor-status $(date +%s)000 1 channels nominal ${channels}"
fi

exit 0
