#!/bin/bash

set -e 

source functions.sh

ROACHES=$(grep '^ *servers_' /etc/corr/* | cut -f2 -d= | tr , '\n'  | tr -d ' '  | sort -u)
declare -a vector

if [ "$1" = "stop" -o "$1" = "start" ] ; then
  i=0; for name in ${ROACHES} ; do vector[$i]=$(echo kcpxport -D ${name}x) ; i=$[i+1] ; done
  if ! kcpcon "${vector[@]}" ; then
    sleep 1
  fi
  
  if [ "$1" = "start" ] ; then
    i=0; for name in ${ROACHES} ; do vector[$i]=$(echo kcpxport -U ${name}x) ; i=$[i+1] ; done
    kcpcon "${vector[@]}"
  fi
else 
  kcs_error "invalid argument"
  exit 1
fi

