#!/bin/bash

set -e 

source functions.sh

ROACHES=$(grep '^ *servers_' /etc/corr/* | cut -f2 -d= | tr , '\n'  | tr -d ' '  | sort -u)

case "$1" in
  start)
    cmd=${startcmd}
    kcs_info "about to start roaches"
    ;;
  stop)
    cmd=${stopcmd}
    kcs_info "about to stop roaches"
    ;;
  *)
    kcs_error "invalid argument"
    exit 1
    ;;
esac


for roach in $(grep roach.*x /etc/hosts | cut -f 1 -d \ ) ; do
  echo -n -e "${cmd}" | netcat -q 2 -w 2 ${roach} 10001 > /dev/null &
  sleep 0.003
done

sleep 3
